### ISSUE TITLE
deprecated gulp-minify-css@1.2.2: Use better "gulp-cssnano" instead. 

### ISSUE THREAD

**Issue by luqin** [luqin/react-component-tools#7]
npm WARN deprecated gulp-minify-css@1.2.2: Use better "gulp-cssnano" instead. https://github.com/ben-eb/gulp-cssnano

**Comment by v3nt** [comment]
did you make any progress with this?

**Comment by luqin** [comment]
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
