### ISSUE TITLE
gulp tasks missing

### ISSUE THREAD

**Issue by ritz078** [luqin/react-component-tools#8]
There are a lot of gulp tasks that are missing like `dev`, `build` .

**Comment by luqin** [comment]
You can have a try with https://github.com/luqin/react-icheck

**Comment by ritz078** [comment]
Its working fine there.

**Comment by luqin** [comment]
Can you show me your config?

**Comment by ritz078** [comment]
Oh got it now. But i think you should keep a default config file and then provide options only if someone wants to change it . 

Since this is a starter kit and not some tool you should be directly able to get started. :)

**Comment by luqin** [comment]
If you run gulp command. Gulp needs a gulp.config.js file. I will write a cli tool to support default tasks: https://github.com/luqin/react-component-tools/tree/master/lib/cli

**Comment by ritz078** [comment]
That will be great. I know thats needed so why noot keep a file by default like any other gulp starter projects ?

**Comment by luqin** [comment]
Yes. U r right.
